### ISSUE TITLE
Preview images of older posts are stretched

### ISSUE THREAD

**Issue by grandesballo** [puresyntax71/hugo-theme-chunky-poster#102]
I was customising the theme because i noticed that older posts in the main page are getting stretched.

I think this is not ideal and I would rather preserve the image aspect ratio by changing .Resize to either .Fill (which keeps the image box aspect ratio and crops the image inside) or .Fit (which changes the image box aspect ratio, but keeps the full image)

**Comment by puresyntax71** [comment]
Yeah, I'll try to check. There was actually a PR for this (#27) but I think I changed it again. I'll try to change it back and try to work around my blog with it.

**Comment by puresyntax71** [comment]
Guess this one is fine now.
