### ISSUE TITLE
RSS icon broken

### ISSUE THREAD

**Issue by puresyntax71** [puresyntax71/hugo-theme-chunky-poster#21]
the rss icon is broken (also on your blog) - I'm not sure why, I tried to fix it myself but got nowhere

**Comment by puresyntax71** [comment]
I might be missing something although I'm not seeing it on the simulator using iOS 12.0:

![Simulator Screen Shot - iPhone XS Max - 2020-01-02 at 13 10 47](https://user-images.githubusercontent.com/34715246/71652564-6b177b00-2d61-11ea-8703-3fa563222b15.png)

**Comment by YL-K** [comment]
Sorry, turns out it's due to me using the "Fanboy’s Annoyance" filter list in uBlock Origin.

**Comment by puresyntax71** [comment]
Oh sweet, you're here. Yeah, good to know. Think I'll just close this one as this isn't a theme issue. The others I have already addressed. Thanks!
