### ISSUE TITLE
Fix multilingual pages

### ISSUE THREAD

**Issue by puresyntax71** [puresyntax71/hugo-theme-chunky-poster#31]
Pages are broken when multiple languages are enabled.

![image](https://user-images.githubusercontent.com/34715246/71872875-a4ccf500-3158-11ea-9756-8f2db355eec1.png)

**Comment by inatus** [comment]
Just for your information, we still have a workaround to display the cover image.

```
[languages]
  [languages.en]
    languageName = "English"
    title = "English Title"
    weight = 1
    [languages.en.params]
      homepageImage = "/images/cover.jpg"

  [languages.ja]
    languageName = "Japanese"
    title = "Japanese Title"
    weight = 2
    [languages.ja.params]
      homepageImage = "../images/cover.jpg"
```

**Comment by puresyntax71** [comment]
Oh, makes sense. Yeah, will try to fix. Seems to be a path issue.
