### ISSUE TITLE
Need help getting the exampleSite working

### ISSUE THREAD

**Issue by rwaal** [puresyntax71/hugo-theme-chunky-poster#51]
I'm just starting out with Hugo and with this theme. With the instructions in the README, I can't get the example site working. Here's what I'm doing:

- create a new hugo site `hugo new site mywebsite`
- initiate git repo `cd mywebsite && git init`
- download the theme `git submodule add https://github.com/puresyntax71/hugo-theme-chunky-poster.git themes/hugo-theme-chunky-poster`
- copy the content of the /themes/hugo-theme-chunky-poster/exampleSite to / (the root of the website)

When running the `hugo server` command it spits allot of message about missing layout files. I noticed there is a layouts folder in the theme's folder, so I copied that. That still doesn't produce a working example site, as can be seen in the demo. 

I'm sure I am missing something. Could you please nudge me in the right direction? 
My goal is to have the theme's examples site up and running as in the demo. From there I will start customising things. 

Many thanks in advance! 😄

**Comment by puresyntax71** [comment]
Ah, guess it's missing the theme selection. You can do `hugo server -t hugo-theme-chunky-poster`. I've also updated [config.toml](exampleSite/config.toml) to include the theme at 19188b25b0640c254a9936ef2e3e6c0529525b3d.

**Comment by rwaal** [comment]
Indeed, it works now! Thanks for the quick response.
