### ISSUE TITLE
Readtime and Wordcount not working

### ISSUE THREAD

**Issue by velasco** [puresyntax71/hugo-theme-chunky-poster#52]
Hi, Im playing around with your theme, which I find great. But apparently Word Count and Read Time is showing no values on the post pages. Do you have an idea, why?

https://5e31af7fb8ec1d000805a002--romantic-nobel-925ac9.netlify.com/

**Comment by puresyntax71** [comment]
That's weird. Off the top of my head, maybe check the language files? I think there should be entries similar to [this](i18n/en.yaml).

**Comment by velasco** [comment]
> That's weird. Off the top of my head, maybe check the language files? I think there should be entries similar to `en.yaml`.
> 
> I am also using the latest version for Hugo.
> 
> Hope that helps.

Thanks a lot, in fact, that fixed my issue. I will need the site to be in German, but I will get around.
