### ISSUE TITLE
overriding styles

### ISSUE THREAD

**Issue by pirator** [puresyntax71/hugo-theme-chunky-poster#60]
Hi,
this is probably a newb/general hugo question but I can't seem to override the stylesheets.

in my site root i made an /src/scss/chunky-poster.scss
also tried /static/src/scss/chunky-poster.scss

...but no joy. Can't even change the background colour!
Do I need to build out the scss files first or is that handled by Hugo?

Cheers,
Pete.

**Comment by puresyntax71** [comment]
Yeah, sorry, I haven't added support for custom styles yet. You can do it like https://github.com/puresyntax71/hugo-theme-chunky-poster/issues/32#issuecomment-572669559. Will try to add support for it this week.

That is for CSS though. If you want SCSS and not fork the project (for recompiling), you can use [Hugo pipelines](https://gohugo.io/hugo-pipes/scss-sass/) instead. This seems easiest.

**Comment by pirator** [comment]
ok got it :)  (so not insane after all)

Cool, this is day 1 of hugo for me today so this might be a project for another time... but with pipelines that would be modifying the stylesheet links in the header to do the conversion on the fly right?

**Comment by puresyntax71** [comment]
Yeah, that is right. It would build the SCSS/SASS files for you and include them in the `head` as long as you've followed the documentation from the link.

**Comment by puresyntax71** [comment]
Got it at #68 . Just copied over the feature from the [Event](https://github.com/olOwOlo/hugo-theme-even) theme.
