### ISSUE TITLE
Title Tag

### ISSUE THREAD

**Issue by benjamin-patch** [puresyntax71/hugo-theme-chunky-poster#70]
The title tag displays the same '.Site.Title' on all pages. This is bad for SEO. The title tag should display unique titles for each page that has been assigned one. For example:
'Markdown Syntax Guide | Hugo Themes'
not:
'Hugo Themes' everywhere.

**Comment by benjamin-patch** [comment]
I am building a new Hugo site with this beautiful theme, and have written a fix for this issue. I would like to contribute that fix to your project.

I have forked the repo, created a new branch, successfully tested the code locally, but I am not able to push the new branch to create a pull request. Authentication fails. Please let me know if there is something else I should be doing. Thank you in advance.

**Comment by benjamin-patch** [comment]
A proposed fix for this issue has been submitted as a pull request (benjamin-patch:title-tag). Previously I was trying to submit the pull request from the git submodule I created within a different Hugo site used for testing. That failed. But with a straight clone of the repo (not a submodule), the issue was resolved.

**Comment by puresyntax71** [comment]
Thanks! I've merged it.

> Authentication fails. Please let me know if there is something else I should be doing. Thank you in advance.

I think it might be because of remote url. Could do `git remote add <name> <your-repo>` and `git push <name>` inside the submodule.

**Comment by benjamin-patch** [comment]
That's great! Happy to be a contributor.

> I think it might be because of remote url. Could do git remote add <name> <your-repo> and git push <name> inside the submodule.

I will have to give that a try as I normally install Hugo themes as git submodules. Seems cleaner that way. Thanks again!
