### ISSUE TITLE
How to use commento

### ISSUE THREAD

**Issue by LeandroPelegrini** [puresyntax71/hugo-theme-chunky-poster#73]
Sorry, but I don't understand how to use commento.
I already maked signup and put my link, but I don't get how to update the link in config.toml
What link shuld I put in "https://somename.commento.io"?
Tks

**Comment by puresyntax71** [comment]
Sorry, I've updated the README. It should've been `url` instead of `theme`.

**Comment by LeandroPelegrini** [comment]
Oh, tks for the update.
