### ISSUE TITLE
params.social email address with double slaches

### ISSUE THREAD

**Issue by justasmundeikis** [puresyntax71/hugo-theme-chunky-poster#86]
Not sure, if this is theme issue, blogdown or HUGO issue, but while we have:  `email = "corona-stat@protonmail.com"` in `config.toml`, when clicking on `email`, email address retrieved is `//corona-stat@protonmail.com` with to slashes...

Our site: https://corona-stat.lt
Github repo: https://github.com/justasmundeikis/corona-stat-lt-blog

**Comment by puresyntax71** [comment]
Yeah, it was the theme. Might want to update. Thanks!
