### ISSUE TITLE
favicon and Page width

### ISSUE THREAD

**Issue by kangzhiheng** [puresyntax71/hugo-theme-chunky-poster#93]
Thx @puresyntax71 , I really like your themes, it's very beautiful. But I have two issues:
- How to modify the page `width` of the post？ I think the default setting is a bit narrow, I do not know in `which file` to modify.
- How to add `favicon` for web pages?

**Comment by chris-gillatt** [comment]
Put the favicon in `static/favicon.ico` and it will be copied to public when it serves.

**Comment by puresyntax71** [comment]
> How to add favicon for web pages?

Yeah, as @chris-gillatt mentioned. I'll also try to add in the path later on.

> How to modify the page width of the post？ I think the default setting is a bit narrow, I do not know in which file to modify.

Might need to override the style here from bootstrap (see the "Customization" section). I guess you can give this a try - https://getbootstrap.com/docs/4.0/layout/grid/#variables.

**Comment by kangzhiheng** [comment]
> Put the favicon in `static/favicon.ico` and it will be copied to public when it serves.

thanks~It worked.

**Comment by kangzhiheng** [comment]
> > How to add favicon for web pages?
> 
> Yeah, as @chris-gillatt mentioned. I'll also try to add in the path later on.
> 
> > How to modify the page width of the post？ I think the default setting is a bit narrow, I do not know in which file to modify.
> 
> Might need to override the style here from bootstrap (see the "Customization" section). I guess you can give this a try - https://getbootstrap.com/docs/4.0/layout/grid/#variables.

@puresyntax71 In `\themes\hugo-theme-chunky-poster\layouts\post\single.html`, location code snippet
```html
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="content">
                            {{ $page.Content }}
                        </div>

                        {{- with $page.Params.tags -}}
                            <div class="tags my-3">
                            {{- range . -}}
                                <a class="badge badge-pill badge-light border mr-2" href="{{ "/tags/" | relLangURL }}{{ . | urlize }}">
                                    <i class="fas fa-tag mr-2"></i>{{ . }}
                                </a>
                            {{- end -}}
                            </div>
                        {{- end -}}

                        {{ partial "sharer.html" . }}
                    </div>
                </div>
```
The default width of page is `<div class="col-lg-8">`，I change `col-lg-8` to `col-lg-12`, the options are `col-lg-8`, `col-lg-10`, `col-lg-12`. `col-lg-12` is great.

**Comment by puresyntax71** [comment]
Ah, totally forgot that one. Good one!
