### ISSUE TITLE
Mmark is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by chris-gillatt** [puresyntax71/hugo-theme-chunky-poster#94]
mmark needs to be replaced as it's due to be decommed:

Found here:
```
content/post/math-typesetting.mmark
7:markup: mmark

themes/hugo-theme-chunky-poster/exampleSite/content/post/math-typesetting.mmark
7:markup: mmark
```
Link: https://gohugo.io//content-management/formats/#list-of-content-formats

**Comment by puresyntax71** [comment]
Yeah, I think I'll put this on hold for now. I might wait for https://github.com/gohugoio/hugoBasicExample once it removes the content from there and will update it here.

**Comment by puresyntax71** [comment]
I guess this is still an ongoing discussion at gohugoio/hugoBasicExample#58. The PR contains removal of the `mmark` content.
