### ISSUE TITLE
Similar css js render issue for Netlify Host

### ISSUE THREAD

**Issue by websitemanager** [puresyntax71/hugo-theme-chunky-poster#97]
First of all your theme is amazing and i have learnt a lot from it.
Trying to play around with it by making a blog. Everything seems to be perfect running local until I serve it to Netlify. Obviously your pipeline is a bit different from what I have been blogging on another 2 years old blog. I have spent hours trying to figure out the problem yet I have to surrender to it coming to seek your help.

I am not sure there are steps i have been missing. Originally I was wondering it was just a problem of relative link. I tried to change the baseURL from "/" to a domain. It seems doesn't work and I have no clues whether i need to change something on the partial/head.html on the href for the min.js and min.css.

Here is the website https://www.nipponhashi.com and I can see the from the console returning .min.js file missing as the href is pointing to dist/blahblahblah.

Did I miss something so that I cannot generate the html properly with a whole link https://www.nipponhashi.com/dist/blah for it?

I am looking forward to seeing your reply soon.

**Comment by puresyntax71** [comment]
Hi,

Thanks for trying it out!

The URLs seem to be correct with the latest updates. Maybe check if `hugo` (instead of `hugo serve`) did build the site correctly? Other than that maybe it has something to do with your Netlify build. Able to post them here?

Other than that as long as you have those files in static/dist (https://github.com/puresyntax71/hugo-theme-chunky-poster/tree/master/static/dist), I think it should've worked.

**Comment by Wojtek-Isakovsky** [comment]
I will come back in a bit and tell you the result later tonight . Thanks for quick reply!

**Comment by websitemanager** [comment]
Building sites … WARN 2020/05/02 19:48:28 Markup type mmark is deprecated and will be removed in a future release. See https://gohugo.io//content-management/formats/#list-of-content-formats

                   | EN  
-------------------+-----
  Pages            | 51  
  Paginator pages  |  0  
  Non-page files   | 10  
  Static files     | 12  
  Processed images |  6  
  Aliases          |  5  
  Sitemaps         |  1  
  Cleaned          |  0  

when I build hugo. I tried yarn build and hugo build as well. No error.

Here is netlify deploy after pushing to GitHub

7:51:15 PM: Build ready to start
7:51:17 PM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
7:51:17 PM: build-image tag: v3.3.7
7:51:17 PM: buildbot version: d305548225ac57bb00eb5a596b0b8674e76a4681
7:51:17 PM: Fetching cached dependencies
7:51:17 PM: Starting to download cache of 155.5MB
7:51:18 PM: Finished downloading cache in 873.099903ms
7:51:18 PM: Starting to extract cache
7:51:25 PM: Finished extracting cache in 6.95279431s
7:51:25 PM: Finished fetching cache in 7.892523998s
7:51:25 PM: Starting to prepare the repo for build
7:51:26 PM: Preparing Git Reference refs/heads/master
7:51:27 PM: Found Netlify configuration file netlify.toml in site root
7:51:27 PM: Found Netlify configuration file(s). Overriding site configuration
7:51:27 PM: Starting build script
7:51:27 PM: Installing dependencies
7:51:27 PM: Started restoring cached node version
7:51:31 PM: Finished restoring cached node version
7:51:31 PM: Attempting node version '8.17.0' from .nvmrc
7:51:32 PM: v8.17.0 is already installed.
7:51:33 PM: Now using node v8.17.0 (npm v6.13.4)
7:51:33 PM: Attempting ruby version 2.6.2, read from environment
7:51:35 PM: Using ruby version 2.6.2
7:51:35 PM: Using PHP version 5.6
7:51:35 PM: Started restoring cached node modules
7:51:35 PM: Finished restoring cached node modules
7:51:35 PM: Started restoring cached yarn cache
7:51:35 PM: Finished restoring cached yarn cache
7:51:36 PM: Installing NPM modules using Yarn version 1.12.1
7:51:36 PM: yarn install v1.12.1
7:51:36 PM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
7:51:36 PM: [1/4] Resolving packages...
7:51:37 PM: success Already up-to-date.
7:51:37 PM: Done in 0.90s.
7:51:37 PM: NPM modules installed using Yarn
7:51:38 PM: Started restoring cached go cache
7:51:38 PM: Finished restoring cached go cache
7:51:38 PM: unset GOOS;
7:51:38 PM: unset GOARCH;
7:51:38 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
7:51:38 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
7:51:38 PM: go version >&2;
7:51:38 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
7:51:38 PM: go version go1.12 linux/amd64
7:51:38 PM: Installing missing commands
7:51:38 PM: Verify run directory
7:51:38 PM: Executing user command: npm run build
7:51:38 PM: > victor-hugo@1.0.0 prebuild /opt/build/repo
7:51:38 PM: > rimraf dist
7:51:38 PM: > victor-hugo@1.0.0 build /opt/build/repo
7:51:38 PM: > npm run build:webpack && npm run build:hugo
7:51:38 PM: > victor-hugo@1.0.0 build:webpack /opt/build/repo
7:51:38 PM: > cross-env NODE_ENV=production webpack --config webpack.prod.js
7:51:42 PM: Hash: 14d63f78a92f0c205631
7:51:42 PM: Version: webpack 4.42.1
7:51:42 PM: Time: 2243ms
7:51:42 PM: Built at: 2020-05-02 11:51:42
7:51:42 PM:          Asset       Size  Chunks                         Chunk Names
7:51:42 PM:    fonts/.keep    0 bytes          [emitted]
7:51:42 PM: main.14d63.css  505 bytes       0  [emitted] [immutable]  main
7:51:42 PM:  main.14d63.js   3.68 KiB       0  [emitted] [immutable]  main
7:51:42 PM: Entrypoint main = main.14d63.css main.14d63.js
7:51:42 PM: [0] ./src/index.js 122 bytes {0} [built]
7:51:42 PM: [1] ./src/css/main.css 714 bytes {0} [built]
7:51:42 PM: [3] ./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./src/css/main.css 39 bytes {0} [built]
7:51:42 PM:     + 2 hidden modules
7:51:42 PM: Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/postcss-loader/src/index.js!node_modules/sass-loader/dist/cjs.js!src/css/main.css:
7:51:42 PM:     Entrypoint mini-css-extract-plugin = *
7:51:42 PM:     [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js!./src/css/main.css 888 bytes {0} [built]
7:51:42 PM:         + 1 hidden module
7:51:43 PM: > victor-hugo@1.0.0 build:hugo /opt/build/repo
7:51:43 PM: > hugo -d ../dist -s site -v
7:51:43 PM: INFO 2020/05/02 11:51:43 Using config file:
7:51:43 PM: Building sites …
7:51:43 PM: INFO 2020/05/02 11:51:43 syncing static files to /opt/build/repo/dist/
7:51:43 PM: WARN 2020/05/02 11:51:43 Markup type mmark is deprecated and will be removed in a future release. See https://gohugo.io//content-management/formats/#list-of-content-formats
7:51:43 PM:                   |
7:51:43 PM:  EN
7:51:43 PM: -
7:51:43 PM: ------------------+
7:51:43 PM: -----
7:51:43 PM: Pages
7:51:43 PM: |
7:51:43 PM: 51
7:51:43 PM: Paginator pages
7:51:43 PM: |
7:51:43 PM:  0
7:51:43 PM: Non-page files
7:51:43 PM: |
7:51:43 PM: 10
7:51:43 PM: Static files
7:51:43 PM: |
7:51:43 PM:  7
7:51:43 PM: Processed images |  6
7:51:43 PM: Aliases          |  5
7:51:43 PM:   Sitemaps         |
7:51:43 PM:  1
7:51:43 PM:   Cleaned          |  0
7:51:43 PM: Total in 115 ms
7:51:43 PM: Skipping functions preparation step: no functions directory set
7:51:43 PM: Caching artifacts
7:51:43 PM: Started saving node modules
7:51:43 PM: Finished saving node modules
7:51:43 PM: Started saving yarn cache
7:51:43 PM: Finished saving yarn cache
7:51:43 PM: Started saving pip cache
7:51:43 PM: Finished saving pip cache
7:51:43 PM: Started saving emacs cask dependencies
7:51:43 PM: Finished saving emacs cask dependencies
7:51:43 PM: Started saving maven dependencies
7:51:43 PM: Finished saving maven dependencies
7:51:43 PM: Started saving boot dependencies
7:51:43 PM: Finished saving boot dependencies
7:51:43 PM: Started saving go dependencies
7:51:43 PM: Finished saving go dependencies
7:51:43 PM: Build script success
7:51:43 PM: Starting to deploy site from 'dist'
7:51:43 PM: Creating deploy tree 
7:51:43 PM: Creating deploy upload records
7:51:43 PM: 0 new files to upload
7:51:43 PM: 0 new functions to upload
7:51:43 PM: Starting post processing
7:51:44 PM: Post processing done
7:51:44 PM: Site is live
7:52:12 PM: Finished processing build request in 54.695220775s

No luck at all. Tried both "/" and domain again.
No error.

I am wondering if we need to modify your theme on head.html for the css and js to something like 
<link rel="stylesheet" href="{{ .Site.BaseURL }}css/style.css"/>
or as a relativeURL?

My previous projects was using the same deployment and the other pipeline and theme could even deploy with just "/", which was a depreciated casper 2 theme.

For your info, I started with boilerplate. Cloned your theme and deleted your .git so as I tried not to use submodule. Everything was fine including modifying bootstraps etc on hugo serve.

I am not sure if I messed up something but I definitely didn't touch the css and js URL on head.html. I added partials for google adsense and probably that's the main modification on head.html inside your theme layout partials.

Do you have any suggestions? Should I try to start from scratch again?

**Comment by websitemanager** [comment]
I used npm install for the beginning of the project as usual. copied some of your example site contents for reference. Changed the front matters of markdown. Modified the config file. Installed yarn so that I can use yarn build as your readme suggested (yarn watch doesn't work).

**Comment by websitemanager** [comment]
this is my package.json

{
  "name": "victor-hugo",
  "version": "1.0.0",
  "description": "Victor Hugo is a Hugo boilerplate for creating truly epic websites!",
  "repository": "netlify/victor-hugo",
  "main": "index.js",
  "scripts": {
    "lint": "eslint src",
    "start": "run-p start:**",
    "start:hugo": "hugo -d ../dist -s site -vw",
    "start:webpack": "webpack-dev-server --config webpack.dev.js --hot",
    "preview": "run-p preview:**",
    "preview:hugo": "npm run start:hugo -- -D -F",
    "preview:webpack": "npm run start:webpack",
    "prebuild": "rimraf dist",
    "build": "npm run build:webpack && npm run build:hugo",
    "build:preview": "npm run build:webpack && npm run build:hugo:preview",
    "build:hugo": "hugo -d ../dist -s site -v",
    "build:hugo:preview": "npm run build:hugo -- -D -F",
    "build:webpack": "cross-env NODE_ENV=production webpack --config webpack.prod.js"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.9.5",
    "@babel/plugin-syntax-object-rest-spread": "^7.8.0",
    "@babel/preset-env": "^7.9.5",
    "@babel/register": "^7.9.0",
    "assets-webpack-plugin": "^3.9.7",
    "babel-eslint": "^10.0.2",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^5.0.3",
    "cross-env": "^5.2.0",
    "css-loader": "^3.4.1",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.18.1",
    "exports-loader": "^0.7.0",
    "fancy-log": "^1.3.2",
    "file-loader": "^4.1.0",
    "hugo-bin": "^0.57.0",
    "imports-loader": "^0.8.0",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.13.1",
    "npm-run-all": "^4.1.5",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "plugin-error": "^1.0.1",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-preset-env": "^6.7.0",
    "rimraf": "^3.0.0",
    "sass-loader": "^8.0.0",
    "style-loader": "^1.1.4",
    "uglifyjs-webpack-plugin": "^2.1.3",
    "url-loader": "^2.1.0",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.6",
    "webpack-dev-server": "^3.10.3",
    "webpack-merge": "^4.1.4",
    "whatwg-fetch": "^3.0.0"
  },
  "resolutions": {
    "natives": "1.1.6"
  }
}

Should I not be using Victor hugo boilerplate from https://github.com/netlify-templates/victor-hugo ?

**Comment by websitemanager** [comment]
Sorry for all the troubles. Highly appreciated

**Comment by puresyntax71** [comment]
Oh that does seem interesting. I haven't tried this kind of build yet though. I think not using victor-hugo and just using a [simple deployment](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/) process would be easiest.

Although if you want to use the boilerplate (but without customizations on the theme), perhaps you can try this:

(assuming `site` directory contains all hugo files):

1. Clone the theme inside `site/themes`. I think just a simple `git clone` and deleting the `.git` directory would do.
2. Replace `build` from `package.json` with `"build": "npm run build:hugo"`.

I don't think you would really need `webpack` here at the moment since you won't be building the assets. If that's the case, I guess there might need more changes since boilerplate has a different process.

Hope that helps.

**Comment by puresyntax71** [comment]
Guess I'll be closing this one. Feel free to re-open again.
