### ISSUE TITLE
Some fontawesome won't appear

### ISSUE THREAD

**Issue by altarfoss** [puresyntax71/hugo-theme-chunky-poster#98]
Hai,

This is my first time to use Hugo 😁️,

I have some trouble when i'm trying to add search icon using `<i class='fa-fw fab fa-search'></i>` the search icon won't appear (they just display exclamation logo with loading bars), <br/>

![Screenshot from 2020-05-03 06-05-21](https://user-images.githubusercontent.com/64653484/80893486-ef244400-8cfc-11ea-90db-bea86c8ebda5.png)

afterward i try to change to `fa-twitter` the twitter logo displaying correctly.

![Screenshot from 2020-05-03 06-01-18](https://user-images.githubusercontent.com/64653484/80893547-7c679880-8cfd-11ea-9d28-02bb1bb30678.png)

**Comment by chrysale** [comment]
I am facing the same problems trying to add a phone icon "fas fa-phone" in footer.html. Any solution yet?

**Comment by puresyntax71** [comment]
Yeah, was trying to use Fontawesome API here so to not load all icons. I'll try to update it next time to load all icons. For now, I guess you can customize [App.js](../blob/master/src/js/App.js) and rebuild the assets. See [Customizations](../blob/master/README.md#customization).

**Comment by chrysale** [comment]
When I try to rebuild the assets with `yarn build` I get an ugly traceback. What is even worse, I haven't got the faintest idea what all this processing is about. So, loading all icons from the start sounds like a great idea to me.

**Comment by altarfoss** [comment]
> Yeah, was trying to use Fontawesome API here so to not load all icons. I'll try to update it next time to load all icons. For now, I guess you can customize [App.js](../blob/master/src/js/App.js) and rebuild the assets. See [Customizations](../blob/master/README.md#customization).

thankyou it works 😊️

**Comment by altarfoss** [comment]
> Yeah, was trying to use Fontawesome API here so to not load all icons. I'll try to update it next time to load all icons. For now, I guess you can customize [App.js](../blob/master/src/js/App.js) and rebuild the assets. See [Customizations](../blob/master/README.md#customization).

thank you it's work, the problem has solved
